name: RSS to SafeW
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RSS_GITHUB_PAT }}
          fetch-depth: 0

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 关键修改：在同一步骤中安装依赖并运行脚本，确保环境一致
      - name: 安装依赖并运行脚本
        env:
          SAFEW_BOT_TOKEN: ${{ secrets.SAFEW_BOT_TOKEN }}
          SAFEW_CHAT_ID: ${{ secrets.SAFEW_CHAT_ID }}
          RSS_FEED_URL: ${{ secrets.RSS_FEED_URL }}
        run: |
          # 强制安装依赖（包括beautifulsoup4）
          pip install --upgrade pip
          pip install feedparser aiohttp beautifulsoup4
          # 验证bs4是否安装成功
          pip list | grep beautifulsoup4
          python -c "from bs4 import BeautifulSoup; print('bs4导入成功')"
          # 运行脚本
          python rss_safew.py

      - name: 提交更新后的ID文件
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "更新已发送的帖子ID"
          file_pattern: "sent_posts.json"
          branch: main
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
