name: RSS to SafeW
on:
  schedule:
    - cron: "*/10 * * * *"  # 每10分钟运行一次
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RSS_GITHUB_PAT }}
          fetch-depth: 0

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 新增：清除pip缓存，避免旧缓存影响
      - name: 清除pip缓存
        run: pip cache purge

      # 强制安装所有依赖（包括beautifulsoup4）
      - name: 安装依赖（含bs4）
        run: |
          pip install --upgrade pip  # 升级pip确保安装正常
          pip install feedparser aiohttp beautifulsoup4

      # 新增：验证依赖是否安装成功（关键调试步骤）
      - name: 检查bs4是否安装
        run: |
          pip list | grep beautifulsoup4  # 输出安装的版本，确认是否存在
          python -c "from bs4 import BeautifulSoup; print('bs4导入成功')"  # 验证能否导入

      - name: 运行SafeW推送脚本
        env:
          SAFEW_BOT_TOKEN: ${{ secrets.SAFEW_BOT_TOKEN }}
          SAFEW_CHAT_ID: ${{ secrets.SAFEW_CHAT_ID }}
          RSS_FEED_URL: ${{ secrets.RSS_FEED_URL }}
        run: python rss_safew.py

      - name: 提交更新后的ID文件
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "更新已发送的帖子ID"
          file_pattern: "sent_posts.json"
          branch: main
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
