name: RSS to SafeW
on:
  schedule:
    - cron: "*/10 * * * *"  # 每10分钟运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RSS_GITHUB_PAT }}
          fetch-depth: 0

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 安装依赖（新增beautifulsoup4）
        run: pip install feedparser aiohttp beautifulsoup4

      - name: 运行SafeW推送脚本
        env:
          SAFEW_BOT_TOKEN: ${{ secrets.SAFEW_BOT_TOKEN }}
          SAFEW_CHAT_ID: ${{ secrets.SAFEW_CHAT_ID }}
          RSS_FEED_URL: ${{ secrets.RSS_FEED_URL }}
        run: python rss_safew.py

      - name: 提交更新后的ID文件
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "更新已发送的帖子ID"
          file_pattern: "sent_posts.json"
          branch: main
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
